### ISSUE TITLE
Taker orders without open orders account

### ISSUE THREAD

**Issue by armaniferrante** [Bonfida/dex-v4#29]
This would be very useful for swap UIs and composing programs that don't want to deal with fees and the added complication of creating/removing an open orders account

**Comment by ellttBen** [comment]
This is definitely doable and might reduce the costs involved with one-off swaps indeed. Functionality like this would probably be going into a new instruction.
I added the `enhancement` label since I think this is definitely the kind of functionality we can easily deploy in a non-breaking manner in production, which means that this issue is non-blocking.

**Comment by ellttBen** [comment]
The `swap` instruction has been added a while ago to address this.
